# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee16984fc80b18eb2b4ab3ff33379a4c86ebeb37d6514cac2c093f213d82223b4c160bd444383ffc320e181c877eaee96395687929559e81605a671193b2b1c5

test:
  secret_key_base: 3e90b26f3bc38b60931dd6645079b14b356e2416146ff0277313f0f37f55d4eb97d3ebd3cc544f02616631d8398a7f0282415c1e838de13364d65c7d2002fe01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
